/* Formatted on 2023-04-06 오후 6:21:49 (QP5 v5.215.12089.38647) */
ROOM_OPTION


DROP  TABLE PROPERTIES
CREATE TABLE PROPERTIES
(
   P_ID            NUMBER (5) NOT NULL primary key,
   P_TITLE         VARCHAR2 (500) NOT NULL,
   P_PHOTO         VARCHAR (1000) NULL,
   P_STAR          VARCHAR2 (20) NOT NULL,
   P_POSTAL        VARCHAR2 (20)  NULL,
   P_TEL           VARCHAR2 (50)  NULL,
   P_ADDRESS       VARCHAR2 (1000) NOT NULL,
   P_OVERVIEW      VARCHAR2 (4000) NULL,
   P_SCALE         VARCHAR2 (200) NULL,
   P_CHECKIN       VARCHAR2 (200)  NULL,
   P_CHECKOUT      VARCHAR2 (200)  NULL,
   P_GUIDE         VARCHAR2 (3000) NULL,
   P_REFUND        VARCHAR2 (1000) NULL,
   P_STATUS        VARCHAR2 (100) NOT NULL,
   P_MAPY          VARCHAR2 (100) NOT NULL,
   P_MAPX          VARCHAR2 (100) NOT NULL,
   P_HIDERDATE     DATE  NOT NULL,
   P_CHANGE_DATE   DATE NULL
);
alter table PROPERTIES
add constraint P_ID primary key;

CREATE TABLE PRO_FACILITIES (
    P_ID    NUMBER(5)     NOT NULL,
    FAC_ROOM    VARCHAR2(500)    NULL   ,
    FAC_RESTARUANT    VARCHAR2(500)  NULL,
    FAC_SECURITY    VARCHAR2(500)     NULL,
    FAC_BATHROOM    VARCHAR2(500)   NULL,
    FAC_PARKING    VARCHAR2(500)    NULL,
    FAC_BED    VARCHAR2(500)   NULL,
    FAC_LIVING    VARCHAR2(500)     NULL,
    FAC_MEDIA    VARCHAR2(500)    NULL,
    FAC_INTERNET    VARCHAR2(500)    NULL,
    FAC_SERVICE    VARCHAR2(500)    NULL,
    FAC_GENERAL    VARCHAR2(500)     NULL,
    FAC_LANGUAGE    VARCHAR2(500)     NULL,
    FAC_KITCHEN    VARCHAR2(500)   NULL,
    FAC_RECEPTION    VARCHAR2(500)   NULL
);
ALTER TABLE PRO_FACILITIES
ADD CONSTRAINT P_ID foreign KEY(P_ID) references PROPERTIES (P_ID);
---------외래키 수정------------
--제약조건 삭제
ALTER TABLE PRO_FACILITIES DROP CONSTRAINT P_ID;
--외래키 수정
ALTER TABLE PRO_FACILITIES MODIFY (P_ID REFERENCES PROPERTIES(P_ID));
--수정된 외래키  제약조건 추기
ALTER TABLE 테이블명 ADD CONSTRAINT 외래키제약조건명 FOREIGN KEY (외래키컬럼명) REFERENCES 참조테이블명(참조컬럼명);

DROP TABLE P_ROOMTYPE 

CREATE TABLE P_ROOMTYPE (
    P_ID    NUMBER(5)  NOT NULL ,
    ROOM_TYPE    VARCHAR2(100)     NOT NULL,
    ROOM_PRICE    VARCHAR2(100)     NOT NULL,
    ROOM_CAPACITY    VARCHAR2(100)   NULL,
    ROOM_OPTION  VARCHAR2(300)   NULL,
     CONSTRAINT fk_P_ID foreign key(P_ID) references PROPERTIES (P_ID)
);
DELETE FROM P_ROOMTYPE;